# Generated by Django 3.0.5 on 2020-04-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0002_auto_20200403_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='3949', verbose_name='URL'),
        ),
    ]
