# Generated by Django 3.0.5 on 2020-04-03 14:49

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0004_auto_20200403_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qa.Answer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='3900', verbose_name='URL'),
        ),
    ]
