# Generated by Django 3.0.5 on 2020-04-04 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0008_auto_20200403_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='answer_set', to='qa.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(unique=True),
        ),
    ]
